[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"

[[redirects]]
  from = "/app-store"
  to = "https://apps.apple.com/pt/app/litten/id1543915955"
  status = 301
  force = false

[[redirects]]
  from = "/play-store"
  to = "https://play.google.com/store/apps/details?id=com.litten"
  status = 301
  force = false
