[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/app-store"
  to = "https://apps.apple.com/pt/app/litten/id1543915955"
  status = 301
  force = false

[[redirects]]
  from = "/play-store"
  to = "https://play.google.com/store/apps/details?id=com.litten"
  status = 301
  force = false
