[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'self'; form-action 'self'; object-src 'none'; frame-ancestors 'self'; worker-src 'self'; child-src 'self'; frame-src 'self'; connect-src 'self'; font-src 'self'; manifest-src 'self'; media-src 'self'; prefetch-src 'self'; require-trusted-types-for 'script'; block-all-mixed-content"

[[redirects]]
  from = "/app-store"
  to = "https://apps.apple.com/pt/app/litten/id1543915955"
  status = 301
  force = false

[[redirects]]
  from = "/play-store"
  to = "https://play.google.com/store/apps/details?id=com.litten"
  status = 301
  force = false
